## Dynamic configuration

http:
  ## middlewares
  middlewares:
    # global-auth : configuration
    global-auth:
      basicAuth:
        realm: "Access denied"
        removeHeader: true
        usersFile: "/etc/traefik/auth-usersfile"
