###
# traefik configuration

## logs
[log]
  level = "INFO"

# configure docker provider
[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false

# configure dynamic providers
[providers.file]
  directory = "/etc/traefik"
  watch = true

# enable dashboard (secure mode)
[api]
  dashboard = true

# define entrypoints
[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.web-secure]
    address = ":443"

# let's encrypt : https
[certificatesResolvers.default-ssl.acme]
  email = "contact@domain.tld"
  storage = "/etc/traefik-ssl/acme.json"
  [certificatesResolvers.default-ssl.acme.dnsChallenge]
    provider = "ovh"
    delayBeforeCheck = "10"
