###
# traefik configuration

## logs
log:
  level: INFO


#accessLog:
#  filePath: "/tmp/traefik.log"


## anonymous usage data
global:
  sendAnonymousUsage: false


## enable ping
ping: {}


## providers
providers:
  # default docker provider
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  # dynamic provider
  file:
    filename: "/etc/traefik/dynamic.yml"
    watch: true


## enable dashboard (secure mode)
api:
  dashboard: true


## enable experimental http3
experimental:
  http3: true


## define entrypoints
entryPoints:
  # for monit (docker image force using port 80)
  web:
    address: ":80"
  # default entrypoint
  web-secure:
    address: ":443"
    http3: {}


## https mode : let's encrypt
certificatesResolvers:
  default-ssl:
    acme:
      email: "contact@domain.tld"
      storage: "/etc/traefik-ssl/acme.json"
      dnsChallenge:
        provider: ovh
        delayBeforeCheck: 10
