---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Dashboard"
subtitle: "Nekoserv"
#logo: "logo.png"
icon: "fas fa-paw" # Optional icon

header: true
#footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
footer: false

columns: 3

# connectivity
connectivityCheck: false

# Optionnal theme customization
theme: default

# Optional custom stylesheet
stylesheet:
  - "assets/external-resources/custom.css"

colors:
  light:
    highlight-primary: "#d0caca"
    highlight-secondary: "#e1dede"
    highlight-hover: "#ececec"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#363636"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#3273dc"
  dark:
    highlight-primary: "#7f7c7c"
    highlight-secondary: "#d0caca"
    highlight-hover: "#e1dede"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#7f7c7c"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#3273dc"

# Optional message
message:
  style: "is-hidden"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/nekoserv-repository/docker"
    target: "_blank" # optional html tag target attribute
  - name: "Docker Hub"
    icon: "fab fa-hubspot"
    url: "https://hub.docker.com/u/nekoserv"
    target: "_blank"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Multimedia management"
    icon: "fab fa-docker"
    items:
      - name: "Aria2"
        icon: "fas fa-file-download"
        subtitle: "Lightweight multi-protocol download utility."
        url: "/aria2/"
        target: "_blank"
      - name: "Flood"
        logo: "/assets/external-resources/flood.png"
        subtitle: "Web UI for fully-automated rTorrent client."
        url: "/flood/"
        target: "_blank"
      - name: "MeTube"
        logo: "/assets/external-resources/metube.png"
        subtitle: "Web GUI for youtube-dl with playlist support."
        url: "/metube/"
        target: "_blank"
      - name: "pyLoad"
        logo: "/assets/external-resources/pyload.png"
        subtitle: "Free and Open Source download manager."
        url: "/pyload/"
        target: "_blank"
      - name: "SABnzbd"
        logo: "/assets/external-resources/sabnzbd.png"
        subtitle: "Free and easy binary newsreader."
        url: "/sabnzbd/"
        target: "_blank"

  - name: " "
    icon: "fab"
    items:
      - name: "Jackett"
        logo: "/assets/external-resources/jackett.png"
        subtitle: "Proxy aggregator for torrent indexers."
        url: "/jackett/"
        target: "_blank"
      - name: "Lidarr"
        logo: "/assets/external-resources/lidarr.png"
        subtitle: "Music collection manager."
        url: "/lidarr/"
        target: "_blank"
      - name: "Medusa"
        logo: "/assets/external-resources/medusa.png"
        subtitle: "Automatic video library manager for TV shows."
        url: "/medusa/"
        target: "_blank"
      - name: "NZBHydra 2"
        logo: "/assets/external-resources/nzbhydra2.png"
        subtitle: "Proxy aggregator for newznab usenet indexers."
        url: "/nzbhydra/"
        target: "_blank"
      - name: "Radarr"
        logo: "/assets/external-resources/radarr.png"
        subtitle: "Movie collection manager."
        url: "/radarr/"
        target: "_blank"

  - name: "Tools"
    icon: "fas fa-tools"
    items:
      - name: "Drone"
        logo: "/assets/external-resources/drone.png"
        subtitle: "Automate software testing and delivery."
        url: "#"
        target: "_blank"
        tag: "dummy"
        tagstyle: "is-hidden drone"
      - name: "Gitea"
        logo: "/assets/external-resources/gitea.png"
        subtitle: "A painless self-hosted Git service."
        url: "#"
        target: "_blank"
        tag: "dummy"
        tagstyle: "is-hidden gitea"
      - name: "Registry UI"
        icon: "fas fa-book"
        subtitle: "UI for your private registry."
        url: "#"
        target: "_blank"
        tag: "dummy"
        tagstyle: "is-hidden registry-mngr"
      - name: "Traefik"
        logo: "/assets/external-resources/traefik.png"
        subtitle: "The cloud-native application proxy."
        url: "/dashboard/"
        target: "_blank"
      - name: "Trilium"
        logo: "/assets/external-resources/trilium.png"
        subtitle: "Build you personal knowledge base."
        url: "/trilium/"
        target: "_blank"
